import { computed, ref, watch } from 'vue'

export const languages = ['LV', 'RU']

const messages = {
  RU: {
    header: {
      desktopNav: [
        { label: 'Услуги', href: '/#services' },
        { label: 'Каталог', href: '/catalog' },
        { label: 'Портфолио', href: '/portfolio' },
        { label: 'О нас', href: '/#about' },
        { label: 'Контакты', href: '/contacts' },
      ],
      mobileNav: [
        { label: 'О нас', href: '/#about' },
        { label: 'Мы предлагаем', href: '/#services' },
        { label: 'Каталог декора', href: '/catalog' },
        { label: 'Для B2B', href: '/b2b-partnership' },
        { label: 'Портфолио', href: '/portfolio' },
        { label: 'Отзывы', href: '/#testimonials' },
        { label: 'Контакты', href: '/contacts' },
      ],
      navAria: 'Основная навигация',
      mobileNavAria: 'Мобильная навигация',
      languageLabel: 'Выбрать язык',
      socialLabel: 'Соцсети',
      catalogCta: 'Каталог декора',
      callAria: 'Позвонить',
      openMenu: 'Открыть меню',
      closeMenu: 'Закрыть меню',
    },
    home: {
      hero: {
        title: 'Идеальный декор вашего события',
        text: 'Арки, фотозоны и цветочные композиции от Zida Ziedi — для свадеб, корпоративов и особенных моментов вашей жизни.',
        catalog: 'Каталог декора',
        contact: 'Связаться с нами',
        download: 'Скачать каталог с примерами оформления',
        downloadAria: 'Скачать каталог',
        imageAlt: 'Арка с цветочным декором',
        catalogAlt: 'Каталог декора',
      },
      marquee:
        'Цветочные арки • Фотозоны • Декор зала • Оформление свадеб • Аренда декора • Искусственные цветы • Фоновые стены • Оформление мероприятий • Цветочные композиции • Корпоративный декор • Индивидуальный дизайн • Оформление сцен • Декор для фотосессий • Цветочные инсталляции • Event-декор • Аренда арок и стен • Флористический декор • Декор под ключ • Быстрый монтаж и демонтаж •',
      about: {
        title: 'Оформляем пространства, создаём впечатления',
        text: 'Мы влюблены в эстетику и детали. Мы не просто оформляем площадки — мы создаём настроение, передаём атмосферу праздника и индивидуальность каждого события.',
        imageAlt: 'Декоративная цветочная арка',
        items: [
          {
            title: 'Индивидуальный подход',
            text: 'Каждая площадка и событие оформляются по вашему стилю и пожеланиям.',
          },
          {
            title: 'Быстрый монтаж и демонтаж',
            text: 'Работаем оперативно, даже при минимальных сроках подготовки.',
          },
          {
            title: 'Только премиум-материалы',
            text: 'Используем искусственные цветы и элементы, неотличимые от живых.',
          },
        ],
      },
      services: {
        eyebrow: 'ОТ УЮТНЫХ ВЕЧЕРИНОК ДО МАСШТАБНЫХ СОБЫТИЙ',
        title: 'Полный спектр цветочного декора для вашего события',
        details: 'Подробнее',
        all: 'Посмотреть все услуги',
        cards: [
          {
            title: 'Оформление мероприятий',
            text: 'Цветочные арки, фотозоны, стены и композиции, которые делают атмосферу торжества по-настоящему волшебной.',
            href: '/professional-event-decor',
          },
          {
            title: 'Аренда декора для праздника',
            text: 'Быстрое оформление любого пространства. Готовые решения и индивидуальные проекты для агентств, площадок и частных клиентов.',
            href: '#contact',
          },
          {
            title: 'Сотрудничество и B2B партнёрство',
            text: 'Работаем с event-компаниями, отелями и организаторами. Предлагаем гибкие условия и постоянную поддержку в реализации.',
            href: '/b2b-partnership',
          },
        ],
      },
      individual: {
        title: 'Индивидуальный декор для любого события',
        text: [
          'Каждая арка, каждая стена, каждая деталь — результат вдохновения и мастерства Zida Ziedi.',
          'Мы поможем превратить любую площадку в место, где хочется праздновать.',
        ],
        cta: 'Заказать оформление',
        imageAlt: 'Индивидуальный декор для любого события',
      },
      gallery: {
        title: 'Создаём атмосферу для любого события',
        text: 'Zida Ziedi оформляет свадьбы, корпоративы, частные и детские праздники, презентации и выставки. Мы подбираем решения под пространство, стиль и настроение — от камерных мероприятий до масштабных торжеств. Каждая работа отражает эстетику, точность и гармонию деталей.',
        cta: 'Посмотреть портфолио',
        openImage: 'Открыть изображение',
        closeImage: 'Закрыть изображение',
        imageAlt: 'Галерея работ Zida Ziedi',
        expandedAlt: 'Увеличенное изображение из галереи',
      },
      stats: {
        title: 'Наши декорации украшают события по всей Балтии',
        text: 'Каждый проект — это внимание к деталям и стремление превзойти ожидания.',
        videoCta: 'Смотреть видео о нашей работе',
        videoPlayAria: 'Воспроизвести видео о нашей работе',
        videoPauseAria: 'Поставить видео о нашей работе на паузу',
        items: [
          { value: '7,600', suffix: 'm²', label: 'Оформленных площадей' },
          { value: '500', suffix: '+', label: 'Проведённых мероприятий' },
          { value: '15', suffix: '+', label: 'Постоянных партнёров' },
        ],
      },
      contact: {
        title: 'Хотите оформить своё событие?',
        description: 'Оставьте заявку, и мы подберём идеальное оформление под ваш стиль и площадку',
        submit: 'Заказать оформление',
        name: 'Ваше имя',
        phone: 'Ваш телефон',
        privacyBefore: 'Отправляя эту форму, вы соглашаетесь, что предоставленные данные будут использованы для связи с вами и обработаны в соответствии с нашей',
        privacyLink: 'Политикой конфиденциальности',
      },
      testimonials: {
        title: 'Отзывы наших клиентов',
        intro: ['Каждое оформление для нас - личная история.', 'Мы благодарны клиентам за доверие и вдохновляющие слова.'],
        cta: 'Читать все отзывы',
        items: [
          {
            text: 'Сотрудничаем с Zida Ziedi уже второй год подряд. Они - наши спасатели перед большими мероприятиями: всегда пунктуальны, с отличным вкусом и гибким подходом. Последний проект - оформление конференции на 300 человек в Риге - выглядел стильно и современно, без лишнего пафоса. Клиенты были в восторге, и мы тоже.',
            author: 'Radisson Blu',
            role: 'Корпоративное оформление, Рига',
          },
          {
            text: 'Нужно было оформить зал всего за день - команда справилась безупречно. Потрясающий результат и внимание к деталям!',
            author: 'Анастасия и Эдгарс',
            role: 'Свадьба, Рига',
          },
          {
            text: 'Я заказывала оформление на юбилей мамы. Хотелось, чтобы все было красиво, но не вычурно. Ребята предложили концепт с кремовыми и персиковыми оттенками - получилось невероятно нежно. Даже гости спрашивали, кто оформлял зал. Спасибо за внимательность, спокойствие и профессионализм.',
            author: 'Анна',
            role: 'Частное мероприятие, Елгава',
          },
          {
            text: 'Для открытия нашего салона нужен был аккуратный, элегантный декор без перегруза. Команда все почувствовала с первого созвона: палитра, композиции и фотозона получились именно такими, как мы представляли. Пространство выглядело дорого и очень цельно.',
            author: 'Мария',
            role: 'Открытие салона, Юрмала',
          },
          {
            text: 'Обращались за оформлением семейного праздника и остались в полном восторге. Все было собрано вовремя, без лишней суеты, а декор выглядел даже лучше, чем на референсах. Очень приятно работать с людьми, которые так внимательно относятся к деталям.',
            author: 'Илзе и Томс',
            role: 'Семейное торжество, Лиепая',
          },
        ],
      },
      video: {
        playAria: 'Воспроизвести видео',
        pauseAria: 'Поставить видео на паузу',
      },
    },
    eventDecor: {
      hero: {
        eyebrow: 'Услуги',
        title: 'Профессиональное оформление мероприятий',
        text: [
          'Арки, фотозоны, цветочные стены и декор, созданный специально для вашего события — свадьбы, корпоратива, юбилея, детского праздника или презентации.',
          'Мы создаём атмосферу, которая остаётся в памяти гостей.',
        ],
        cta: 'Получить предложение',
        imageAlt: 'Цветочные арки для оформления мероприятий',
      },
      benefits: {
        title: 'Там, где важны атмосфера и красота',
        text: [
          'Zida Ziedi создаёт декор, который превращает любое событие в запоминающееся пространство.',
          'Мы оформляем свадьбы, корпоративы, частные праздники, детские мероприятия и выставки — от небольших камерных вечеринок до крупных событий на сотни гостей.',
          'Каждый проект продумывается индивидуально: мы подбираем цветовые сочетания, формы, композиции и элементы, которые идеально подходят вашей площадке и стилю мероприятия.',
          'Мы работаем с премиальными искусственными цветами и декоративными конструкциями, создавая инсталляции, которые выглядят эффектно и вживую, и на фотографиях.',
          'Наш подход — сочетание вкуса, аккуратного монтажа и понимания атмосферы, которую вы хотите передать.',
        ],
        items: [
          {
            title: 'Свадьбы и выездные церемонии',
            description: 'арки, композиции, фотозоны, оформление зала.',
          },
          {
            title: 'Корпоративные мероприятия',
            description: 'стильный декор, фотозоны, брендированные элементы.',
          },
          {
            title: 'Детские праздники и вечеринки',
            description: 'нежные и яркие инсталляции, тематические фотозоны.',
          },
          {
            title: 'Частные торжества и юбилеи',
            description: 'гармоничное оформление для уютной и тёплой атмосферы.',
          },
          {
            title: 'Презентации, выставки, открытия',
            description: 'выразительные цветочные стены, акцентные композиции, визуальные точки притяжения.',
          },
          {
            title: 'Фотозоны и декорации для съёмок',
            description: 'композиции, которые создают выразительный фон и настроение.',
          },
        ],
      },
      portfolio: {
        title: 'Как выглядят оформленные нами события',
        text: 'От свадебных арок до корпоративных фотозон — каждая работа создаётся вручную и с вниманием к детали.',
        cta: 'Связаться с нами',
        imageAlts: [
          'Белое оформление свадебного ужина на открытом воздухе',
          'Нежная цветочная композиция в пастельных оттенках',
          'Оформление фотозоны с белыми цветами и металлической рамой',
          'Фактурная стена из крупных кремовых роз',
          'Высокая центральная цветочная композиция для банкета',
        ],
      },
      video: {
        eyebrow: '#BACKSTAGE',
        title: 'Магия, которая остаётся за кадром',
        text: 'Короткое видео о том, как мы работаем: создаём, собираем и устанавливаем инсталляции любой сложности.',
        playAria: 'Воспроизвести backstage-видео',
        pauseAria: 'Поставить backstage-видео на паузу',
      },
    },
    b2b: {
      hero: {
        eyebrow: 'Zida Ziedi - надежный партнер',
        title: 'Сотрудничество для агентств, площадок и организаторов',
        text: 'Мы создаем выразительный декор, который помогает вам предлагать клиентам стильные и готовые решения.',
        cta: 'Получить предложение',
        videoCta: 'Смотреть видео о нашей работе',
        videoPlayAria: 'Воспроизвести видео о нашей работе',
        videoPauseAria: 'Поставить видео о нашей работе на паузу',
      },
      audience: {
        eyebrow: '#С КЕМ МЫ РАБОТАЕМ',
        title: 'Мы работаем с профессионалами event-индустрии',
        text: [
          'Мы работаем с теми, кому важно качество декора, стабильность и предсказуемый результат.',
          'Мы берём на себя оформление, чтобы вы могли сосредоточиться на организации и работе с клиентом.',
        ],
        cards: [
          'Event-агентства',
          'Банкетные залы',
          'Отели\nи конгресс-центры',
          'Рекламные\nи продакшн-агентства',
          'Фотостудии и площадки\nдля съемок',
          'Организаторы свадеб\nи частных праздников',
        ],
      },
      capabilities: {
        title: 'Наши возможности для агентств и площадок',
        text: [
          'Мы помогаем партнёрам предлагать клиентам стильный и готовый декор без лишних хлопот.',
          'Команда Zida Ziedi берёт на себя весь процесс — от идеи и подбора элементов до монтажа и вывоза.',
          'Вы получаете надёжного подрядчика, который всегда вовремя и всегда красиво.',
        ],
        items: [
          {
            number: '01',
            title: 'Аренда\nцветочного декора',
            text: 'Арки, стены, фотозоны и композиции из искусственных цветов премиального качества.',
          },
          {
            number: '02',
            title: 'Индивидуальные проекты\nпод вашу задачу',
            text: 'Создаём инсталляции под бренд, тематику или стиль клиента.',
          },
          {
            number: '03',
            title: 'Монтаж и демонтаж\nв сжатые сроки',
            text: 'Работаем быстро, рабочие бригады выезжают по всей Балтии.',
          },
          {
            number: '04',
            title: 'Готовые решения\nдля ежедневных съемок',
            text: 'Фоторум, студии, шоурумы — стабильный красивый декор без ручных обновлений.',
          },
          {
            number: '05',
            title: 'Гибкие условия\nсотрудничества',
            text: 'Спецтарифы, удобная логистика, возможность срочных заказов.',
          },
        ],
        imageAlts: [
          'Пример оформления площадки цветочными композициями',
          'Высокая декоративная композиция для фотозоны',
          'Декоративная инсталляция с зелёными элементами',
          'Декоративная композиция для брендированной зоны',
        ],
      },
      whyUs: {
        eyebrow: '#ПОЧЕМУ МЫ',
        title: 'Преимущества, которые оценят профессионалы',
        text: 'Короткое видео о том, как мы работаем: создаём, собираем и устанавливаем инсталляции любой сложности.',
        items: [
          'Чёткое соблюдение сроков и договорённостей',
          'Премиальное качество искусственных цветов',
          'Готовые комплекты для разных типов событий',
          'Работа по всей Латвии и Балтии',
          'Эстетика, которая усиливает ваш продукт и бренд',
          'Эффектный декор, который ценят клиенты и гости',
          'Прозрачные цены и долгосрочные условия',
          'Быстрая реакция и оперативный монтаж',
          'Гарантия качества и предсказуемый результат',
        ],
      },
      showcase: {
        title: 'Декор, который говорит сам за себя',
        text: 'Свадьбы, корпоративы, презентации, выставки и фотозоны — мы оформляем пространства любого масштаба.',
        imageAlts: [
          'Белая фотозона с мягким диваном и цветами',
          'Круглая декоративная арка с подвесными кристаллами',
          'Прозрачная свадебная табличка с белым декором',
          'Высокая белая инсталляция с тканями и цветами',
          'Приветственная свадебная табличка с белыми цветами',
        ],
      },
      contact: {
        title: 'Хотите предложить клиентам стильный и готовый декор?',
        description: 'Оставьте заявку — мы подготовим специальные условия для агентств и площадок и подберём решения под ваш формат работы.',
        submit: 'Связаться с нами',
      },
    },
    portfolio: {
      eyebrow: '#Наши работы',
      title: 'Портфолио',
      text: 'Только реальные фотографии реализованных проектов.',
      filters: [
        { key: 'all', label: 'Все' },
        { key: 'weddings', label: 'Свадьбы' },
        { key: 'photozones', label: 'Фотозоны' },
        { key: 'decor', label: 'Декор' },
      ],
      imageAlt: 'Портфолио Zida Ziedi',
      openImage: 'Открыть изображение',
      showMore: 'Показать еще',
      closeImage: 'Закрыть изображение',
      expandedAlt: 'Увеличенное изображение из портфолио',
    },
    catalog: {
      eyebrow: '#Каталог',
      title: 'Аренда декора',
      sidebarAria: 'Фильтры каталога',
      filterTitle: 'Тип декора',
      categoryLabel: 'Категория',
      reset: 'Сбросить фильтры',
      sortByPrice: 'Сортировать по цене',
      sortByPopular: 'Сортировать по популярности',
      popular: 'По популярности',
      productLink: 'Перейти в товар',
      showMore: 'Показать еще',
      categories: [
        { label: 'Цветочные арки', value: 'all' },
        { label: 'Арки', value: 'arches' },
        { label: 'Фотозоны', value: 'photozones' },
        { label: 'Декор столов', value: 'table-decor' },
      ],
      products: {
        ledArch18: 'Каркасная LED арка 1.8 м',
      },
      badges: {
        hitSeason: 'Хит сезона',
      },
      contact: {
        title: 'Хотите оформить своё мероприятие?',
        description: 'Оставьте заявку, и мы подберём идеальное оформление под ваш стиль и площадку.',
      },
    },
    contacts: {
      eyebrow: '#Обсудим',
      title: 'Контактная информация',
      text: 'Вы можете связаться с нами любым удобным для вас способом или оставить заявку через форму ниже — мы свяжемся с вами в ближайшее время.',
      successTitle: 'Спасибо!',
      successText: 'Благодарим Вас за обращение! Мы уже получили ваше сообщение и в скором времени свяжемся по указанным вами контактам.',
      sendAgain: 'Отправить еще',
      name: 'Ваше имя',
      city: 'Город',
      service: 'Выбрать услугу',
      phone: 'Ваш телефон',
      message: 'Сообщение',
      submit: 'Заказать оформление',
      privacy: 'Отправляя форму, вы соглашаетесь, что предоставленные данные будут использованы для связи с вами и обработаны в соответствии с Политикой конфиденциальности.',
      callUs: 'Звоните нам',
      writeUs: 'Пишите нам',
      visitUs: 'Заходите к нам',
      socials: 'Мы в соцсетях',
      cityOptions: ['Рига', 'Юрмала', 'Лиепая', 'Даугавпилс'],
      serviceOptions: ['Оформление свадеб', 'Корпоративы', 'Фотозоны', 'Аренда декора'],
    },
    product: {
      category: 'Цветочные арки',
      title: 'Каркасная арка White Elegance PBR22',
      size: 'Размер - 240cm x 220cm',
      badge: 'Хит сезона',
      previousImage: 'Предыдущее изображение',
      nextImage: 'Следующее изображение',
      showImage: 'Показать изображение',
      imageAlts: [
        'Каркасная арка White Elegance PBR22 с белыми цветами',
        'Каркасная арка White Elegance PBR22 крупным планом',
        'Каркасная арка White Elegance PBR22 как центральный декор церемонии',
      ],
      colors: {
        blue: 'Голубой',
        purple: 'Фиолетовый',
        pink: 'Розовый',
      },
      recommendedTitle: 'Рекомендованные варианты использования',
      recommendedUsage: [
        'Центральный элемент зоны церемонии',
        'Фон для стола молодоженов',
        'Фотозона',
      ],
      description: 'Арка выполнена с использованием качественных искусственных цветов, которые выглядят реалистично и сохраняют аккуратный вид на протяжении всего мероприятия. Конструкция подходит для фотосъёмки, церемоний и торжественных событий, эффектно смотрится как вживую, так и на фотографиях.',
      colorTitle: 'Цветовая сочетаемость',
      contact: {
        title: 'Хотите оформить своё мероприятие?',
        description: 'Оставьте заявку, и мы подберём идеальное оформление под ваш стиль и площадку.',
        name: 'Ваше имя',
        phone: 'Ваш телефон',
        submit: 'Заказать оформление',
        privacyBefore: 'Отправляя эту форму, вы соглашаетесь, что предоставленные данные будут использованы для связи с вами и обработаны в соответствии с нашей',
        privacyLink: 'Политикой конфиденциальности',
      },
      addToOrder: 'Добавить в заказ',
    },
    quiz: {
      introBadge: 'Всего за 1 минуту',
      introTitle: 'Подберём декор и покажем ориентировочную смету',
      start: 'Начать',
      steps: {
        eventType: 'Какой тип мероприятия вы планируете?',
        venue: 'Дата и формат площадки',
        guests: 'Количество гостей',
        decorate: 'Что нужно украсить?',
        style: 'Стиль и пышность',
        palette: 'Цветовая палитра',
        flowers: 'Искусственные или живые',
        services: 'Услуги',
        budget: 'Бюджет и ожидания',
        restrictions: 'Условия и ограничения',
        contacts: 'Контакты для сметы',
      },
      dateLabel: 'Выберите дату',
      otherPlaceholder: 'Напишите свое',
      fullnessLabel: 'Планируемая пышность',
      timeLabel: 'Окна времени',
      restrictionsLabel: 'Есть ли запреты площадки (свечи, крепления к стенам, конфетти и т.п.)',
      documentsLabel: 'Нужны ли документы (счёт/договор)',
      namePlaceholder: 'Ваше имя',
      channelLabel: 'Предпочтительный канал связи',
      referencePlaceholder: 'Ссылка на референс (Pinterest и т.п.)',
      submit: 'Получить предложение',
      resultTitle: 'Ориентировочная стоимость',
      packageLabel: 'Пакет',
      includesTitle: 'Что входит',
      exactCalculation: 'Получить точный расчёт',
      requestDate: 'Запросить свободную дату',
      notSelected: 'Не выбрано',
      notSelectedPlural: 'Не выбраны',
      dateNotSelected: 'Не выбрана',
      contactEmpty: 'Не заполнено',
      yes: 'Есть',
      no: 'Нет',
      needed: 'Нужны',
      notNeeded: 'Не нужны',
      notSpecified: 'Не указан',
      eventTypes: {
        wedding: 'Свадьба',
        corporate: 'Корпоратив',
        birthday: 'День рождения',
        anniversary: 'Юбилей',
        presentation: 'Презентация',
        other: 'Другое',
      },
      venues: {
        restaurant: 'Ресторан',
        countryside: 'Загород',
        apartment: 'Квартира',
        hotel: 'Отель',
        outdoor: 'Открытая площадка',
      },
      guests: {
        upto20: 'до 20',
        from20to50: '20 - 50',
        from50to100: '50 - 100',
        from100to200: '100 - 200',
        over200: '200 +',
      },
      decorate: {
        welcome: 'Welcome-зона / вход',
        photozone: 'Фотозона (стена / арка / неон)',
        ceremony: 'Арка / зона церемонии',
        mainTable: 'Президиум / main table',
        guestTables: 'Гостевые столы (центральные композиции)',
        hanging: 'Потолочные / подвесные композиции',
        bouquet: 'Букет / бутоньерки',
      },
      styles: {
        classic: 'Классика',
        modern: 'Modern',
        minimal: 'Минимал',
        luxury: 'Luxury',
        boho: 'Boho',
      },
      palettes: {
        cream: 'Белый / Крем',
        green: 'Белый + Зелень',
        pastel: 'Пастель',
        bright: 'Яркая',
        bordeaux: 'Бордо',
        lavender: 'Лаванда',
        brand: 'Под бренд',
      },
      flowerTypes: {
        decor: 'Декор',
        live: 'Живые',
        mix: 'Микс',
      },
      services: {
        pickup: 'Самовывоз',
        delivery: 'Доставка',
        setup: 'Монтаж',
      },
      timeWindows: {
        morning: 'Утро',
        day: 'День',
        evening: 'Вечер',
      },
      budgets: {
        low: '€300–700',
        medium: '€700–1500',
        high: '€1500–3000',
        premium: '€3000+',
        custom: 'Хочу понять по факту',
      },
      channels: {
        phone: 'Телефон',
        whatsapp: 'WhatsApp',
        telegram: 'Telegram',
        email: 'Email',
      },
      fullness: ['Минимальная', 'Легкая', 'Средняя', 'Пышная', 'Максимальная'],
      resultLabels: {
        eventType: 'Тип мероприятия',
        date: 'Дата',
        venue: 'Формат',
        guests: 'Количество гостей',
        decorate: 'Что украсить',
        style: 'Стиль',
        fullness: 'Пышность',
        palette: 'Цветовая палитра',
        flowers: 'Цветы',
        services: 'Услуги',
        timeWindow: 'Окно времени',
        budget: 'Бюджет',
        contact: 'Контакт',
        channels: 'Канал связи',
        documents: 'Документы',
        restrictions: 'Ограничения',
        reference: 'Референс',
      },
      packages: {
        baseDescriptionStart: 'Базовая сборка под формат',
        baseDescriptionEnd: 'с главным визуальным акцентом и выбранной палитрой.',
        mainZone: 'Главная зона оформления',
        palette: 'Палитра',
        style: 'Стиль',
        wowDescriptionStart: 'Расширенный вариант с пышностью',
        wowDescriptionEnd: 'и полным набором выбранных зон.',
        services: 'Услуги',
        coordination: 'Координация оформления на площадке',
        flowers: 'Цветы',
      },
    },
    footer: {
      tagline: 'Идеальный декор для вашего особенного события',
      servicesTitle: 'Услуги',
      companyTitle: 'Компания',
      contactsTitle: 'Контакты',
      serviceLinks: ['Оформление свадеб', 'Корпоративы', 'Фотозоны', 'Цветочные арки', 'Аренда декора'],
      companyLinks: ['О нас', 'Портфолио', 'Отзывы', 'Контакты', 'Terms & Conditions'],
      copyright: '© 2025 Zida Ziedi. Все права защищены.',
      terms: 'Условия использования',
      privacy: 'Политика конфиденциальности',
    },
  },
  LV: {
    header: {
      desktopNav: [
        { label: 'Pakalpojumi', href: '/#services' },
        { label: 'Katalogs', href: '/catalog' },
        { label: 'Portfolio', href: '/portfolio' },
        { label: 'Par mums', href: '/#about' },
        { label: 'Kontakti', href: '/contacts' },
      ],
      mobileNav: [
        { label: 'Par mums', href: '/#about' },
        { label: 'Ko piedāvājam', href: '/#services' },
        { label: 'Dekoru katalogs', href: '/catalog' },
        { label: 'B2B sadarbība', href: '/b2b-partnership' },
        { label: 'Portfolio', href: '/portfolio' },
        { label: 'Atsauksmes', href: '/#testimonials' },
        { label: 'Kontakti', href: '/contacts' },
      ],
      navAria: 'Galvenā navigācija',
      mobileNavAria: 'Mobilā navigācija',
      languageLabel: 'Izvēlēties valodu',
      socialLabel: 'Sociālie tīkli',
      catalogCta: 'Dekoru katalogs',
      callAria: 'Zvanīt',
      openMenu: 'Atvērt izvēlni',
      closeMenu: 'Aizvērt izvēlni',
    },
    home: {
      hero: {
        title: 'Ideāls dekors jūsu notikumam',
        text: 'Arkas, foto zonas un ziedu kompozīcijas no Zida Ziedi — kāzām, korporatīviem pasākumiem un īpašiem dzīves mirkļiem.',
        catalog: 'Dekoru katalogs',
        contact: 'Sazināties ar mums',
        download: 'Lejupielādēt katalogu ar noformējuma piemēriem',
        downloadAria: 'Lejupielādēt katalogu',
        imageAlt: 'Arka ar ziedu dekoru',
        catalogAlt: 'Dekoru katalogs',
      },
      marquee:
        'Ziedu arkas • Foto zonas • Zāļu dekors • Kāzu noformējums • Dekora noma • Mākslīgie ziedi • Fona sienas • Pasākumu noformēšana • Ziedu kompozīcijas • Korporatīvais dekors • Individuāls dizains • Skatuvju noformējums • Fotosesiju dekors • Ziedu instalācijas • Event dekors • Arku un sienu noma • Floristikas dekors • Dekors uz atslēgas • Ātra montāža un demontāža •',
      about: {
        title: 'Noformējam telpas, radām iespaidus',
        text: 'Mēs mīlam estētiku un detaļas. Mēs ne tikai noformējam vietas — mēs radām noskaņu, svētku atmosfēru un katra notikuma individualitāti.',
        imageAlt: 'Dekoratīva ziedu arka',
        items: [
          {
            title: 'Individuāla pieeja',
            text: 'Katra vieta un notikums tiek noformēts atbilstoši jūsu stilam un vēlmēm.',
          },
          {
            title: 'Ātra montāža un demontāža',
            text: 'Strādājam operatīvi arī tad, ja sagatavošanai atlicis pavisam maz laika.',
          },
          {
            title: 'Tikai premium materiāli',
            text: 'Izmantojam mākslīgos ziedus un elementus, kas izskatās kā dzīvi.',
          },
        ],
      },
      services: {
        eyebrow: 'NO MĀJĪGĀM SVINĪBĀM LĪDZ LIELIEM PASĀKUMIEM',
        title: 'Pilns ziedu dekora klāsts jūsu pasākumam',
        details: 'Uzzināt vairāk',
        all: 'Apskatīt visus pakalpojumus',
        cards: [
          {
            title: 'Pasākumu noformēšana',
            text: 'Ziedu arkas, foto zonas, sienas un kompozīcijas, kas svētku atmosfēru padara patiesi īpašu.',
            href: '/professional-event-decor',
          },
          {
            title: 'Dekora noma svētkiem',
            text: 'Ātrs jebkuras telpas noformējums. Gatavi risinājumi un individuāli projekti aģentūrām, vietām un privātiem klientiem.',
            href: '#contact',
          },
          {
            title: 'Sadarbība un B2B partnerība',
            text: 'Strādājam ar event aģentūrām, viesnīcām un organizatoriem. Piedāvājam elastīgus nosacījumus un pastāvīgu atbalstu realizācijā.',
            href: '/b2b-partnership',
          },
        ],
      },
      individual: {
        title: 'Individuāls dekors jebkuram notikumam',
        text: [
          'Katra arka, katra siena un katra detaļa ir Zida Ziedi iedvesmas un meistarības rezultāts.',
          'Mēs palīdzēsim pārvērst jebkuru vietu par telpu, kurā gribas svinēt.',
        ],
        cta: 'Pasūtīt noformējumu',
        imageAlt: 'Individuāls dekors jebkuram notikumam',
      },
      gallery: {
        title: 'Radām atmosfēru jebkuram notikumam',
        text: 'Zida Ziedi noformē kāzas, korporatīvos, privātos un bērnu svētkus, prezentācijas un izstādes. Mēs piemeklējam risinājumus telpai, stilam un noskaņai — no kamerpasākumiem līdz vērienīgām svinībām. Katrs darbs atspoguļo estētiku, precizitāti un detaļu harmoniju.',
        cta: 'Apskatīt portfolio',
        openImage: 'Atvērt attēlu',
        closeImage: 'Aizvērt attēlu',
        imageAlt: 'Zida Ziedi darbu galerija',
        expandedAlt: 'Palielināts galerijas attēls',
      },
      stats: {
        title: 'Mūsu dekori rotā pasākumus visā Baltijā',
        text: 'Katrs projekts ir uzmanība detaļām un vēlme pārsniegt gaidas.',
        videoCta: 'Skatīties video par mūsu darbu',
        videoPlayAria: 'Atskaņot video par mūsu darbu',
        videoPauseAria: 'Apturēt video par mūsu darbu',
        items: [
          { value: '7,600', suffix: 'm²', label: 'Noformētu platību' },
          { value: '500', suffix: '+', label: 'Aizvadītu pasākumu' },
          { value: '15', suffix: '+', label: 'Pastāvīgu partneru' },
        ],
      },
      contact: {
        title: 'Vēlaties noformēt savu pasākumu?',
        description: 'Atstājiet pieteikumu, un mēs piemeklēsim ideālu noformējumu jūsu stilam un norises vietai',
        submit: 'Pasūtīt noformējumu',
        name: 'Jūsu vārds',
        phone: 'Jūsu tālrunis',
        privacyBefore: 'Nosūtot šo formu, jūs piekrītat, ka sniegtie dati tiks izmantoti saziņai ar jums un apstrādāti saskaņā ar mūsu',
        privacyLink: 'Privātuma politiku',
      },
      testimonials: {
        title: 'Mūsu klientu atsauksmes',
        intro: ['Katrs noformējums mums ir personīgs stāsts.', 'Esam pateicīgi klientiem par uzticību un iedvesmojošiem vārdiem.'],
        cta: 'Lasīt visas atsauksmes',
        items: [
          {
            text: 'Ar Zida Ziedi sadarbojamies jau otro gadu. Viņi ir mūsu glābiņš pirms lieliem pasākumiem: vienmēr precīzi, ar lielisku gaumi un elastīgu pieeju. Pēdējais projekts — konferences noformējums 300 cilvēkiem Rīgā — izskatījās stilīgi un mūsdienīgi, bez lieka patosa. Klienti bija sajūsmā, un mēs arī.',
            author: 'Radisson Blu',
            role: 'Korporatīvais noformējums, Rīga',
          },
          {
            text: 'Vajadzēja noformēt zāli tikai vienas dienas laikā — komanda tika galā nevainojami. Lielisks rezultāts un uzmanība detaļām!',
            author: 'Anastasija un Edgars',
            role: 'Kāzas, Rīga',
          },
          {
            text: 'Pasūtīju noformējumu mammas jubilejai. Gribējās, lai viss būtu skaisti, bet ne pārspīlēti. Komanda piedāvāja konceptu krēmīgos un persiku toņos — sanāca neticami maigi. Pat viesi jautāja, kurš noformēja zāli. Paldies par uzmanību, mieru un profesionalitāti.',
            author: 'Anna',
            role: 'Privāts pasākums, Jelgava',
          },
          {
            text: 'Mūsu salona atklāšanai bija vajadzīgs akurāts, elegants dekors bez pārslodzes. Komanda visu sajuta jau pirmajā sarunā: palete, kompozīcijas un foto zona izdevās tieši tādas, kā iedomājāmies. Telpa izskatījās dārgi un ļoti vienoti.',
            author: 'Marija',
            role: 'Salona atklāšana, Jūrmala',
          },
          {
            text: 'Vērsāmies pēc ģimenes svētku noformējuma un bijām sajūsmā. Viss tika sagatavots laikā, bez liekas steigas, un dekors izskatījās pat labāk nekā atsaucēs. Ir ļoti patīkami strādāt ar cilvēkiem, kuri tik rūpīgi attiecas pret detaļām.',
            author: 'Ilze un Toms',
            role: 'Ģimenes svinības, Liepāja',
          },
        ],
      },
      video: {
        playAria: 'Atskaņot video',
        pauseAria: 'Apturēt video',
      },
    },
    eventDecor: {
      hero: {
        eyebrow: 'Pakalpojumi',
        title: 'Profesionāla pasākumu noformēšana',
        text: [
          'Arkas, foto zonas, ziedu sienas un dekors, kas radīts tieši jūsu notikumam — kāzām, korporatīvam pasākumam, jubilejai, bērnu svētkiem vai prezentācijai.',
          'Mēs radām atmosfēru, kas paliek viesu atmiņā.',
        ],
        cta: 'Saņemt piedāvājumu',
        imageAlt: 'Ziedu arkas pasākumu noformēšanai',
      },
      benefits: {
        title: 'Tur, kur svarīga atmosfēra un skaistums',
        text: [
          'Zida Ziedi rada dekoru, kas jebkuru notikumu pārvērš atmiņā paliekošā telpā.',
          'Noformējam kāzas, korporatīvos pasākumus, privātus svētkus, bērnu pasākumus un izstādes — no nelielām kamerballītēm līdz lieliem notikumiem simtiem viesu.',
          'Katrs projekts tiek pārdomāts individuāli: piemeklējam krāsu salikumus, formas, kompozīcijas un elementus, kas ideāli atbilst jūsu norises vietai un pasākuma stilam.',
          'Strādājam ar premium mākslīgajiem ziediem un dekoratīvām konstrukcijām, veidojot instalācijas, kas izskatās iespaidīgi gan klātienē, gan fotogrāfijās.',
          'Mūsu pieeja ir gaumes, akurātas montāžas un izpratnes par vēlamo atmosfēru apvienojums.',
        ],
        items: [
          {
            title: 'Kāzas un izbraukuma ceremonijas',
            description: 'arkas, kompozīcijas, foto zonas, zāles noformējums.',
          },
          {
            title: 'Korporatīvie pasākumi',
            description: 'stilīgs dekors, foto zonas, zīmola elementi.',
          },
          {
            title: 'Bērnu svētki un ballītes',
            description: 'maigas un spilgtas instalācijas, tematiskas foto zonas.',
          },
          {
            title: 'Privāti svētki un jubilejas',
            description: 'harmonisks noformējums mājīgai un siltai atmosfērai.',
          },
          {
            title: 'Prezentācijas, izstādes, atklāšanas',
            description: 'izteiksmīgas ziedu sienas, akcenta kompozīcijas un vizuāli pievilkšanas punkti.',
          },
          {
            title: 'Foto zonas un dekorācijas filmēšanai',
            description: 'kompozīcijas, kas rada izteiksmīgu fonu un noskaņu.',
          },
        ],
      },
      portfolio: {
        title: 'Kā izskatās mūsu noformētie pasākumi',
        text: 'No kāzu arkām līdz korporatīvām foto zonām — katrs darbs tiek veidots ar rokām un uzmanību detaļām.',
        cta: 'Sazināties ar mums',
        imageAlts: [
          'Balts kāzu vakariņu noformējums brīvā dabā',
          'Maiga ziedu kompozīcija pasteļtoņos',
          'Foto zonas noformējums ar baltiem ziediem un metāla rāmi',
          'Faktūraina siena no lielām krēmkrāsas rozēm',
          'Augsta centrālā ziedu kompozīcija banketam',
        ],
      },
      video: {
        eyebrow: '#BACKSTAGE',
        title: 'Maģija, kas paliek aiz kadra',
        text: 'Īss video par to, kā mēs strādājam: radām, komplektējam un uzstādām dažādas sarežģītības instalācijas.',
        playAria: 'Atskaņot backstage video',
        pauseAria: 'Apturēt backstage video',
      },
    },
    b2b: {
      hero: {
        eyebrow: 'Zida Ziedi - uzticams partneris',
        title: 'Sadarbība aģentūrām, norises vietām un organizatoriem',
        text: 'Mēs radām izteiksmīgu dekoru, kas palīdz jums piedāvāt klientiem stilīgus un gatavus risinājumus.',
        cta: 'Saņemt piedāvājumu',
        videoCta: 'Skatīties video par mūsu darbu',
        videoPlayAria: 'Atskaņot video par mūsu darbu',
        videoPauseAria: 'Apturēt video par mūsu darbu',
      },
      audience: {
        eyebrow: '#AR KO MĒS STRĀDĀJAM',
        title: 'Mēs strādājam ar event nozares profesionāļiem',
        text: [
          'Mēs strādājam ar tiem, kam svarīga dekora kvalitāte, stabilitāte un paredzams rezultāts.',
          'Mēs uzņemamies noformēšanu, lai jūs varētu koncentrēties uz organizēšanu un darbu ar klientu.',
        ],
        cards: [
          'Event aģentūras',
          'Banketu zāles',
          'Viesnīcas\nun kongresu centri',
          'Reklāmas\nun producēšanas aģentūras',
          'Fotostudijas un vietas\nfilmēšanai',
          'Kāzu un privātu svētku\norganizatori',
        ],
      },
      capabilities: {
        title: 'Mūsu iespējas aģentūrām un norises vietām',
        text: [
          'Mēs palīdzam partneriem piedāvāt klientiem stilīgu un gatavu dekoru bez liekām rūpēm.',
          'Zida Ziedi komanda uzņemas visu procesu — no idejas un elementu piemeklēšanas līdz montāžai un izvešanai.',
          'Jūs iegūstat uzticamu izpildītāju, kas vienmēr strādā laikā un vienmēr skaisti.',
        ],
        items: [
          {
            number: '01',
            title: 'Ziedu dekora\nnoma',
            text: 'Arkas, sienas, foto zonas un kompozīcijas no premium kvalitātes mākslīgajiem ziediem.',
          },
          {
            number: '02',
            title: 'Individuāli projekti\njūsu uzdevumam',
            text: 'Veidojam instalācijas zīmolam, tematikai vai klienta stilam.',
          },
          {
            number: '03',
            title: 'Montāža un demontāža\nīsos termiņos',
            text: 'Strādājam ātri, brigādes dodas izbraukumos pa visu Baltiju.',
          },
          {
            number: '04',
            title: 'Gatavi risinājumi\nikdienas filmēšanai',
            text: 'Fotorūmiem, studijām un šovrūmiem — stabils, skaists dekors bez manuālas atjaunošanas.',
          },
          {
            number: '05',
            title: 'Elastīgi sadarbības\nnosacījumi',
            text: 'Īpaši tarifi, ērta loģistika un iespēja veikt steidzamus pasūtījumus.',
          },
        ],
        imageAlts: [
          'Norises vietas noformējuma piemērs ar ziedu kompozīcijām',
          'Augsta dekoratīva kompozīcija foto zonai',
          'Dekoratīva instalācija ar zaļiem elementiem',
          'Dekoratīva kompozīcija zīmolotai zonai',
        ],
      },
      whyUs: {
        eyebrow: '#KĀPĒC MĒS',
        title: 'Priekšrocības, ko novērtēs profesionāļi',
        text: 'Īss video par to, kā mēs strādājam: radām, komplektējam un uzstādām dažādas sarežģītības instalācijas.',
        items: [
          'Precīza termiņu un vienošanos ievērošana',
          'Premium kvalitātes mākslīgie ziedi',
          'Gatavi komplekti dažādiem notikumu tipiem',
          'Darbs visā Latvijā un Baltijā',
          'Estētika, kas pastiprina jūsu produktu un zīmolu',
          'Iespaidīgs dekors, ko novērtē klienti un viesi',
          'Caurspīdīgas cenas un ilgtermiņa nosacījumi',
          'Ātra reakcija un operatīva montāža',
          'Kvalitātes garantija un paredzams rezultāts',
        ],
      },
      showcase: {
        title: 'Dekors, kas runā pats par sevi',
        text: 'Kāzas, korporatīvie pasākumi, prezentācijas, izstādes un foto zonas — mēs noformējam jebkura mēroga telpas.',
        imageAlts: [
          'Balta foto zona ar mīkstu dīvānu un ziediem',
          'Apaļa dekoratīva arka ar piekārtiem kristāliem',
          'Caurspīdīga kāzu zīme ar baltu dekoru',
          'Augsta balta instalācija ar audumiem un ziediem',
          'Sagaidīšanas kāzu zīme ar baltiem ziediem',
        ],
      },
      contact: {
        title: 'Vēlaties piedāvāt klientiem stilīgu un gatavu dekoru?',
        description: 'Atstājiet pieteikumu — mēs sagatavosim īpašus nosacījumus aģentūrām un norises vietām un piemeklēsim risinājumus jūsu darba formātam.',
        submit: 'Sazināties ar mums',
      },
    },
    portfolio: {
      eyebrow: '#Mūsu darbi',
      title: 'Portfolio',
      text: 'Tikai reālas fotogrāfijas no īstenotiem projektiem.',
      filters: [
        { key: 'all', label: 'Visi' },
        { key: 'weddings', label: 'Kāzas' },
        { key: 'photozones', label: 'Foto zonas' },
        { key: 'decor', label: 'Dekors' },
      ],
      imageAlt: 'Zida Ziedi portfolio',
      openImage: 'Atvērt attēlu',
      showMore: 'Parādīt vēl',
      closeImage: 'Aizvērt attēlu',
      expandedAlt: 'Palielināts attēls no portfolio',
    },
    catalog: {
      eyebrow: '#Katalogs',
      title: 'Dekora noma',
      sidebarAria: 'Kataloga filtri',
      filterTitle: 'Dekora tips',
      categoryLabel: 'Kategorija',
      reset: 'Atiestatīt filtrus',
      sortByPrice: 'Kārtot pēc cenas',
      sortByPopular: 'Kārtot pēc popularitātes',
      popular: 'Pēc popularitātes',
      productLink: 'Doties uz produktu',
      showMore: 'Parādīt vēl',
      categories: [
        { label: 'Ziedu arkas', value: 'all' },
        { label: 'Arkas', value: 'arches' },
        { label: 'Foto zonas', value: 'photozones' },
        { label: 'Galdu dekors', value: 'table-decor' },
      ],
      products: {
        ledArch18: 'Karkasa LED arka 1.8 m',
      },
      badges: {
        hitSeason: 'Sezonas hits',
      },
      contact: {
        title: 'Vēlaties noformēt savu pasākumu?',
        description: 'Atstājiet pieteikumu, un mēs piemeklēsim ideālu noformējumu jūsu stilam un norises vietai.',
      },
    },
    contacts: {
      eyebrow: '#Apspriedīsim',
      title: 'Kontaktinformācija',
      text: 'Jūs varat sazināties ar mums sev ērtā veidā vai atstāt pieteikumu zemāk esošajā formā — mēs ar jums sazināsimies tuvākajā laikā.',
      successTitle: 'Paldies!',
      successText: 'Paldies par jūsu ziņu! Mēs to jau esam saņēmuši un drīzumā sazināsimies, izmantojot norādītos kontaktus.',
      sendAgain: 'Nosūtīt vēlreiz',
      name: 'Jūsu vārds',
      city: 'Pilsēta',
      service: 'Izvēlēties pakalpojumu',
      phone: 'Jūsu tālrunis',
      message: 'Ziņojums',
      submit: 'Pasūtīt noformējumu',
      privacy: 'Nosūtot formu, jūs piekrītat, ka jūsu sniegtie dati tiks izmantoti saziņai un apstrādāti saskaņā ar Privātuma politiku.',
      callUs: 'Zvaniet mums',
      writeUs: 'Rakstiet mums',
      visitUs: 'Apmeklējiet mūs',
      socials: 'Mēs sociālajos tīklos',
      cityOptions: ['Rīga', 'Jūrmala', 'Liepāja', 'Daugavpils'],
      serviceOptions: ['Kāzu noformējums', 'Korporatīvie pasākumi', 'Foto zonas', 'Dekora noma'],
    },
    product: {
      category: 'Ziedu arkas',
      title: 'Karkasa arka White Elegance PBR22',
      size: 'Izmērs - 240cm x 220cm',
      badge: 'Sezonas hits',
      previousImage: 'Iepriekšējais attēls',
      nextImage: 'Nākamais attēls',
      showImage: 'Parādīt attēlu',
      imageAlts: [
        'Karkasa arka White Elegance PBR22 ar baltiem ziediem',
        'Karkasa arka White Elegance PBR22 tuvplānā',
        'Karkasa arka White Elegance PBR22 kā ceremonijas centrālais dekors',
      ],
      colors: {
        blue: 'Gaiši zils',
        purple: 'Violets',
        pink: 'Rozā',
      },
      recommendedTitle: 'Ieteicamie izmantošanas varianti',
      recommendedUsage: [
        'Centrālais elements ceremonijas zonā',
        'Fons jaunlaulāto galdam',
        'Foto zona',
      ],
      description: 'Arka ir veidota, izmantojot kvalitatīvus mākslīgos ziedus, kas izskatās reālistiski un saglabā akurātu izskatu visa pasākuma laikā. Konstrukcija ir piemērota fotosesijām, ceremonijām un svinīgiem notikumiem, izskatoties iespaidīgi gan klātienē, gan fotogrāfijās.',
      colorTitle: 'Krāsu saderība',
      contact: {
        title: 'Vēlaties noformēt savu pasākumu?',
        description: 'Atstājiet pieteikumu, un mēs piemeklēsim ideālu noformējumu jūsu stilam un norises vietai.',
        name: 'Jūsu vārds',
        phone: 'Jūsu tālrunis',
        submit: 'Pasūtīt noformējumu',
        privacyBefore: 'Nosūtot šo formu, jūs piekrītat, ka sniegtie dati tiks izmantoti saziņai ar jums un apstrādāti saskaņā ar mūsu',
        privacyLink: 'Privātuma politiku',
      },
      addToOrder: 'Pievienot pasūtījumam',
    },
    quiz: {
      introBadge: 'Tikai 1 minūtē',
      introTitle: 'Piemeklēsim dekoru un parādīsim orientējošu tāmi',
      start: 'Sākt',
      steps: {
        eventType: 'Kādu pasākuma veidu jūs plānojat?',
        venue: 'Datums un norises vietas formāts',
        guests: 'Viesu skaits',
        decorate: 'Ko nepieciešams noformēt?',
        style: 'Stils un kuplums',
        palette: 'Krāsu palete',
        flowers: 'Mākslīgie vai dzīvie',
        services: 'Pakalpojumi',
        budget: 'Budžets un gaidas',
        restrictions: 'Nosacījumi un ierobežojumi',
        contacts: 'Kontakti tāmei',
      },
      dateLabel: 'Izvēlieties datumu',
      otherPlaceholder: 'Ierakstiet savu variantu',
      fullnessLabel: 'Plānotais kuplums',
      timeLabel: 'Laika logs',
      restrictionsLabel: 'Vai norises vietai ir aizliegumi (sveces, stiprinājumi pie sienām, konfeti u.tml.)',
      documentsLabel: 'Vai nepieciešami dokumenti (rēķins/līgums)',
      namePlaceholder: 'Jūsu vārds',
      channelLabel: 'Vēlamais saziņas kanāls',
      referencePlaceholder: 'Saite uz atsauci (Pinterest u.tml.)',
      submit: 'Saņemt piedāvājumu',
      resultTitle: 'Orientējošās izmaksas',
      packageLabel: 'Pakete',
      includesTitle: 'Kas iekļauts',
      exactCalculation: 'Saņemt precīzu aprēķinu',
      requestDate: 'Pieprasīt brīvu datumu',
      notSelected: 'Nav izvēlēts',
      notSelectedPlural: 'Nav izvēlēti',
      dateNotSelected: 'Nav izvēlēts',
      contactEmpty: 'Nav aizpildīts',
      yes: 'Ir',
      no: 'Nav',
      needed: 'Nepieciešami',
      notNeeded: 'Nav nepieciešami',
      notSpecified: 'Nav norādīts',
      eventTypes: {
        wedding: 'Kāzas',
        corporate: 'Korporatīvs pasākums',
        birthday: 'Dzimšanas diena',
        anniversary: 'Jubileja',
        presentation: 'Prezentācija',
        other: 'Cits',
      },
      venues: {
        restaurant: 'Restorāns',
        countryside: 'Ārpus pilsētas',
        apartment: 'Dzīvoklis',
        hotel: 'Viesnīca',
        outdoor: 'Atklāta norises vieta',
      },
      guests: {
        upto20: 'līdz 20',
        from20to50: '20 - 50',
        from50to100: '50 - 100',
        from100to200: '100 - 200',
        over200: '200 +',
      },
      decorate: {
        welcome: 'Welcome zona / ieeja',
        photozone: 'Foto zona (siena / arka / neons)',
        ceremony: 'Arka / ceremonijas zona',
        mainTable: 'Prezidijs / main table',
        guestTables: 'Viesu galdi (centrālās kompozīcijas)',
        hanging: 'Griestu / piekārtās kompozīcijas',
        bouquet: 'Pušķis / boutonniere',
      },
      styles: {
        classic: 'Klasika',
        modern: 'Modern',
        minimal: 'Minimāls',
        luxury: 'Luxury',
        boho: 'Boho',
      },
      palettes: {
        cream: 'Balts / Krēms',
        green: 'Balts + zaļumi',
        pastel: 'Pastelis',
        bright: 'Spilgta',
        bordeaux: 'Bordo',
        lavender: 'Lavanda',
        brand: 'Pēc zīmola',
      },
      flowerTypes: {
        decor: 'Dekors',
        live: 'Dzīvie',
        mix: 'Mikss',
      },
      services: {
        pickup: 'Pašizvešana',
        delivery: 'Piegāde',
        setup: 'Montāža',
      },
      timeWindows: {
        morning: 'Rīts',
        day: 'Diena',
        evening: 'Vakars',
      },
      budgets: {
        low: '€300–700',
        medium: '€700–1500',
        high: '€1500–3000',
        premium: '€3000+',
        custom: 'Vēlos saprast pēc fakta',
      },
      channels: {
        phone: 'Tālrunis',
        whatsapp: 'WhatsApp',
        telegram: 'Telegram',
        email: 'Email',
      },
      fullness: ['Minimāls', 'Viegls', 'Vidējs', 'Kupls', 'Maksimāls'],
      resultLabels: {
        eventType: 'Pasākuma veids',
        date: 'Datums',
        venue: 'Formāts',
        guests: 'Viesu skaits',
        decorate: 'Ko noformēt',
        style: 'Stils',
        fullness: 'Kuplums',
        palette: 'Krāsu palete',
        flowers: 'Ziedi',
        services: 'Pakalpojumi',
        timeWindow: 'Laika logs',
        budget: 'Budžets',
        contact: 'Kontakts',
        channels: 'Saziņas kanāls',
        documents: 'Dokumenti',
        restrictions: 'Ierobežojumi',
        reference: 'Atsauce',
      },
      packages: {
        baseDescriptionStart: 'Pamata komplekts formātam',
        baseDescriptionEnd: 'ar galveno vizuālo akcentu un izvēlēto paleti.',
        mainZone: 'Galvenā noformējuma zona',
        palette: 'Palete',
        style: 'Stils',
        wowDescriptionStart: 'Paplašināts variants ar kuplumu',
        wowDescriptionEnd: 'un pilnu izvēlēto zonu komplektu.',
        services: 'Pakalpojumi',
        coordination: 'Noformējuma koordinēšana norises vietā',
        flowers: 'Ziedi',
      },
    },
    footer: {
      tagline: 'Ideāls dekors jūsu īpašajam notikumam',
      servicesTitle: 'Pakalpojumi',
      companyTitle: 'Uzņēmums',
      contactsTitle: 'Kontakti',
      serviceLinks: ['Kāzu noformējums', 'Korporatīvie pasākumi', 'Foto zonas', 'Ziedu arkas', 'Dekora noma'],
      companyLinks: ['Par mums', 'Portfolio', 'Atsauksmes', 'Kontakti', 'Terms & Conditions'],
      copyright: '© 2025 Zida Ziedi. Visas tiesības aizsargātas.',
      terms: 'Lietošanas noteikumi',
      privacy: 'Privātuma politika',
    },
  },
}

const getInitialLanguage = () => {
  if (typeof window === 'undefined') return 'LV'

  const savedLanguage = window.localStorage.getItem('zieda-language')
  return languages.includes(savedLanguage) ? savedLanguage : 'LV'
}

const currentLanguage = ref(getInitialLanguage())

const setLanguage = (language) => {
  if (!languages.includes(language)) return
  currentLanguage.value = language
}

watch(
  currentLanguage,
  (language) => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language.toLowerCase()
    }

    if (typeof window !== 'undefined') {
      window.localStorage.setItem('zieda-language', language)
    }
  },
  { immediate: true },
)

export const useLanguage = () => ({
  currentLanguage,
  languages,
  setLanguage,
  t: computed(() => messages[currentLanguage.value]),
})
